/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EnrollmentRouteImport } from './routes/enrollment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstancesIdRouteImport } from './routes/instances.$id'

const EnrollmentRoute = EnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesIdRoute = InstancesIdRouteImport.update({
  id: '/instances/$id',
  path: '/instances/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enrollment': typeof EnrollmentRoute
  '/instances/$id': typeof InstancesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enrollment': typeof EnrollmentRoute
  '/instances/$id': typeof InstancesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/enrollment': typeof EnrollmentRoute
  '/instances/$id': typeof InstancesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/enrollment' | '/instances/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/enrollment' | '/instances/$id'
  id: '__root__' | '/' | '/enrollment' | '/instances/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnrollmentRoute: typeof EnrollmentRoute
  InstancesIdRoute: typeof InstancesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/enrollment': {
      id: '/enrollment'
      path: '/enrollment'
      fullPath: '/enrollment'
      preLoaderRoute: typeof EnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances/$id': {
      id: '/instances/$id'
      path: '/instances/$id'
      fullPath: '/instances/$id'
      preLoaderRoute: typeof InstancesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnrollmentRoute: EnrollmentRoute,
  InstancesIdRoute: InstancesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
